site_name: Pentesting Taskforce ☠️
site_url: https://hcoco1.github.io/Pentesting-Taskforce/
theme:
  name: material
  font:
    text: Roboto
  icon:
    logo: material/library
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
  plugins:
    - social
    - search

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: indigo
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/weather-night
        name: Switch to light mode    
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/hcoco1
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hcoco1
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hcoco1/
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - abbr
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - mkdocs-pdf
  - social:
      cards_layout: default
  
extra_css:
  - 'custom.css'

copyright: |
  &copy; 2024 <a href="https://www.hcoco1.com"  target="_blank" rel="noopener">Ivan Arias</a>